---
name: "build"

on:
  release:
    types: [published, created, edited]
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: "linzeyan"
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          tags: ${{ github.ref_name }}, latest
